== Install Container Tools and Podman

In this lab, you will install Grafana, a browser-based data dashboard,
in two ways. First, you will install and run it through the RHEL web
console. After that, you will install and configure the Grafana
container through Podman’s command line interface (CLI).

First, install RHEL Container Tools by running the following command:

[source,bash,run]
----
dnf install -y container-tools
----

Container Tools includes Podman along with other applications that make
it easier to manage containers on RHEL, and it is available for all RHEL
subscriptions, including the free
https://developers.redhat.com/articles/faqs-no-cost-red-hat-enterprise-linux#[Developer
Subscription for Individuals]. To learn more about Podman, check out
this helpful
https://developers.redhat.com/cheat-sheets/podman-cheat-sheet[Podman
Cheat Sheet].

Start Podman using `+systemctl+`

[source,bash,run]
----
systemctl start podman
----

Using `+systemctl+`, allow Podman to start every time the system boots:

[source,bash,run]
----
systemctl enable podman
----
